name: geostories
description: GeoStories Application
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.2
  geolocator: ^9.0.2
  font_awesome_flutter: ^10.4.0
  provider: ^6.0.5
  flutter_bloc: ^8.1.1
  shared_preferences: ^2.0.17
  language_picker: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/dev_group_image.jpg
