// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7oZ5kq5IbeBprO6YUoy8W0Pvwz5g26ZA',
    appId: '1:666685128396:web:af4b49138031b92f3b8c69',
    messagingSenderId: '666685128396',
    projectId: 'geostories-test',
    authDomain: 'geostories-test.firebaseapp.com',
    storageBucket: 'geostories-test.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS5jhJjVqrIzg6Z-li58s96unBJ1bOoLw',
    appId: '1:666685128396:android:c4651afa78219e443b8c69',
    messagingSenderId: '666685128396',
    projectId: 'geostories-test',
    storageBucket: 'geostories-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd4pke1educsM1HDMn8xwgrS5ZW--oaiE',
    appId: '1:666685128396:ios:76051b74f11811f23b8c69',
    messagingSenderId: '666685128396',
    projectId: 'geostories-test',
    storageBucket: 'geostories-test.appspot.com',
    androidClientId: '666685128396-c4b2qmrksvjuqdgd4cjedobe3p68gd6s.apps.googleusercontent.com',
    iosClientId: '666685128396-v0j0bnrrr1vpqlqel6sn9jvfp1a1sffv.apps.googleusercontent.com',
    iosBundleId: 'com.example.geostories',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDd4pke1educsM1HDMn8xwgrS5ZW--oaiE',
    appId: '1:666685128396:ios:76051b74f11811f23b8c69',
    messagingSenderId: '666685128396',
    projectId: 'geostories-test',
    storageBucket: 'geostories-test.appspot.com',
    androidClientId: '666685128396-c4b2qmrksvjuqdgd4cjedobe3p68gd6s.apps.googleusercontent.com',
    iosClientId: '666685128396-v0j0bnrrr1vpqlqel6sn9jvfp1a1sffv.apps.googleusercontent.com',
    iosBundleId: 'com.example.geostories',
  );
}
